nineninecats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats

end

nineninecats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

nineninecats/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :bigint           not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#


require 'action_view'
class Cat < ApplicationRecord
    include ActionView::Helpers::DateHelper

    COLORS = [
        "orange",
        "white",
        "black",
        "purple"
    ]

    validates :birth_date, :color, :name, :sex, :description, presence: true
    validates :color, inclusion: COLORS
    validates :sex, inclusion: ["M", "F"]

    def age
       distance_of_time_in_words(self.birth_date, Time.now)
    end


end

nineninecats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

nineninecats/app/controllers/cats_controller.rb
class CatsController < ApplicationController

    def index
        @cats = Cat.order(:name)
        render :index
    end

    def show
        @cat = Cat.find(params[:id])

        if @cat
            render :show
       else
            render :index
           
       end

    end

    def new

        render :new

    end

    def edit
        
        render :edit

    end

    def create
        @cat = Cat.new(cat_params)
        if @cat.save
            render :show
        else 
            render :new
        end
    end

    def update
        @cat = Cat.find_by(id: params[:id])
        if @cat.update(cat_params)
            redirect_to cat_url(@cat)
        else
            render :edit
        end
    end

    def destroy
        @cat = Cat.find_by(id: params[:id])
        cat.destroy
        render :index

    end

    private
    def cat_params
        params.require(:cat).permit(:birth_date, :name, :color, :sex, :description)
    end
end

nineninecats/app/helpers/application_helper.rb
module ApplicationHelper
end

nineninecats/app/helpers/cats_helper.rb
module CatsHelper
end

nineninecats/app/views/cats/index.html.erb
<h1> Come see all the cats! </h1>


<ul>
  <% @cats.each do |cat| %>
    <li><a href="<%= cats_url(cat.id) %>"> <%= cat.name %> </a></li>
  <% end %>
</ul>

nineninecats/app/views/cats/show.html.erb
<head>
    <style>
table, th, td { 
  border: 1px solid black;
  
}



body {
  text-align: center;
}

table.center {
    margin-left: auto;
     margin-right: auto;
    }

    </style>
</head>



<body>

    <h1> Cat Info </h1>
    <h2> Name: <%= @cat.name %> </h2>
    <p> Bio: <%= @cat.description %> </p>
    <img src= "<%= @cat.image_url %>"
     width="300" 
     height= auto />
    <br>


    <table class = center>
        <thead >
            <tr>
                <th>Attribute</th>
                <th>Info</th>
            </tr>

        </thead>
        <tbody>

            <tr>
            <td> Age </td>
            <td> <%= @cat.age %> </td>
            </tr>
            <tr>
            <td> Birthday </td>
            <td> <%= @cat.birth_date.strftime("%m/%d/%Y") %> </td>
            </tr>
            <tr>
            <td> Gender </td>
            <td> <%= @cat.sex %> </td>
            </tr>
            <tr>
            <td> Color</td>
            <td> <%= @cat.color %> </td>
            </tr>
            
        </tbody>

        
    </table>
</body>

nineninecats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nineninecats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>